# PROJETO E-COMMERCE FAKE
Este projeto gera dados fake de clientes (utilizando o pacote **faker**) alimentando um banco de dados com registros de compras em uma empresa E-Commerce fictícia de produtos da cultura Geek e Nerd para estados do Brasil.

### Bibliotecas utilizadas:

In [1]:
import sqlite3
from faker import Faker
import random
from datetime import datetime, timedelta
import csv
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
import pandas as pd

In [ ]:
# Criação do dicionário com produtos e preços
produtos = {
    "Vestuário": {
        "Camisa Temática": 44.90,
        "Moletom": 98.90,
        "Boné": 39.90,
        "pijama": 85.90
    },
    "Action Figures e Colecionáveis": {
        "Action Figure": 180.50,
        "Funko Pop": 80.50,
        "Estatueta": 350.10,
        "Coleção de Figurinhas": 91.90
    },
    "Canecas e Utensílios": {
        "Caneca Personalizada": 29.90,
        "Copo Térmico": 39.90,
        "Jogo de Pratos e Talheres Temático": 19.90,
        "chaveiro": 10.75
    },
    "Leituras": {
        "Mangá": 36.90,
        "Quadrinho": 34.90,
        "Graphic Novel": 49.90,
        "Livro": 59.90
    },
    "Jogos de Tabuleiro": {
        "Jogo de Estratégia": 98.70,
        "Jogo de Cartas": 29.50,
        "Jogo de Festa": 62.40,
        "conjunto de dados RPG": 30.50
    },
    "Acessórios para Cosplay": {
        "Máscara": 49.90,
        "Fantasia": 112.50,
        "Peruca": 39.90,
        "Acessórios e adereços": 27.80
    },
    "Posters e Decoração": {
        "Poster": 45.50,
        "Quadro Decorativo": 39.60,
        "Adesivo de Parede": 24.90,
        "Luminária personalizada":250.10
    },
    "Jogos de Video Game": {
        "Jogo para Console": 109.90,
        "Acessório para Jogo": 89.90,
        "Console clássico": 999.90,
        "Console Portátil": 350.90
    },
     "Acessórios de Informática": {
        "Jogos para PC": 99.90,
        "Pendrive":34.90,
        "Teclado": 49.90,
        "Mouse": 39.90
    }
}

In [3]:
# Criação do dicionário com DDDs e estados
ddd_estados = {
    '11': 'São Paulo', '12': 'São Paulo', '13': 'São Paulo', '14': 'São Paulo',
    '15': 'São Paulo', '16': 'São Paulo', '17': 'São Paulo', '18': 'São Paulo',
    '19': 'São Paulo', '21': 'Rio de Janeiro', '22': 'Rio de Janeiro', '24': 'Rio de Janeiro',
    '27': 'Espírito Santo', '28': 'Espírito Santo', '31': 'Minas Gerais', '32': 'Minas Gerais',
    '33': 'Minas Gerais', '34': 'Minas Gerais', '35': 'Minas Gerais', '37': 'Minas Gerais',
    '38': 'Minas Gerais', '41': 'Paraná', '42': 'Santa Catarina', '43': 'Paraná',
    '44': 'Paraná', '45': 'Paraná', '46': 'Paraná', '47': 'Santa Catarina',
    '48': 'Santa Catarina', '49': 'Santa Catarina', '51': 'Mato Grosso', '52': 'Goiás',
    '53': 'Distrito Federal', '61': 'Distrito Federal', '62': 'Goiás', '63': 'Tocantins',
    '64': 'Goiás', '65': 'Mato Grosso', '66': 'Mato Grosso', '67': 'Mato Grosso do Sul',
    '68': 'Acre', '69': 'Acre', '71': 'Bahia', '73': 'Bahia', '74': 'Bahia', '75': 'Bahia',
    '77': 'Bahia', '79': 'Sergipe', '81': 'Pernambuco', '82': 'Alagoas', '83': 'Paraíba',
    '84': 'Rio Grande do Norte', '85': 'Ceará', '86': 'Piauí', '87': 'Pernambuco',
    '88': 'Ceará', '89': 'Piauí', '91': 'Pará', '92': 'Amazonas', '93': 'Pará',
    '94': 'Pará', '95': 'Roraima', '96': 'Amapá', '97': 'Amazonas', '98': 'Maranhão',
    '99': 'Maranhão'
}

In [4]:
# Conectar ao banco de dados (ou criar um novo)
conn = sqlite3.connect('empresa.db')
cursor = conn.cursor()

In [5]:
# Criar tabela de compras se não existir
cursor.execute('''CREATE TABLE IF NOT EXISTS compras (
    id_cliente INTEGER PRIMARY KEY AUTOINCREMENT,
    cliente TEXT NOT NULL,
    idade INTEGER NOT NULL,
    telefone TEXT NOT NULL,
    estado TEXT NOT NULL,
    DataCompra DATE NOT NULL,
    produto TEXT NOT NULL,
    preco REAL NOT NULL,
    unidades INTEGER NOT NULL,
    ValorCompra REAL NOT NULL)''')
print("Tabela criada com sucesso!")

Tabela criada com sucesso!

In [6]:
# Transformar dados para Português-br
fake = Faker('pt_BR')

In [7]:
#Gerar data que foi efetuada a compra pelo cliente
def gerar_data_compra():
    # Gera uma data aleatória entre 1 e 30 de outubro de 2024
    start_date = datetime(2024,12,1)
    end_date = datetime(2024,12,31)
    random_date = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    return random_date.date()  # Retorna a data no formato YYYY-MM-DD

In [8]:
# Gerar números de telefone de clientes
def gerar_telefone():
    ddd = fake.random_element(elements=list(ddd_estados.keys()))
    numero = fake.random_int(min=10000000, max=99999999)
    estado = ddd_estados[ddd]
    return f"({ddd}) {numero}", estado

In [9]:
# Gera e insere 2.500 registros
for _ in range(2500):
    nome_completo = f"{fake.first_name()} {fake.last_name()}" # Primeiro e último nome do cliente
    idade = fake.random_int(min=18, max=50) # Idade mínima de 18 anos e máxima de 50 anos
    telefone, estado = gerar_telefone()
    data_compra = gerar_data_compra()
    
    # Seleciona um produto aleatório do dicionário
    categoria = random.choice(list(produtos.keys()))
    produto = random.choice(list(produtos[categoria].keys()))
    
    preco = round(produtos[categoria][produto], 2)  # Preço fixo
    
    unidades = random.randint(1, 10)  # Número de unidades compradas (1 a 10)
    # Calcula o valor da compra
    valor_compra = round(preco * unidades, 2)
    # Inserindo dados no banco de dados
    try:
        cursor.execute('''INSERT INTO compras (cliente, idade, telefone, estado, DataCompra, produto, preco, unidades, ValorCompra)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)''',
            (nome_completo, idade, telefone, estado, data_compra, produto, preco, unidades, valor_compra))
    except sqlite3.Error as e:
        print(f"Erro ao inserir dados: {e}")
# Salvar (commit) as alterações
conn.commit()
print("Dados inseridos com sucesso!")
warnings.filterwarnings('ignore')

Dados inseridos com sucesso!

In [10]:
cursor.execute("SELECT * FROM compras")
compras = cursor.fetchall()
# Gerar arquivo CSV
with open('registros.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Escrever o cabeçalho
    writer.writerow(['ID Cliente', 'Cliente', 'Idade', 'Telefone', 'Estado', 'DataCompra', 'Produto', 'Preço', 'Unidades', 'ValorCompra'])
    # Escrever os dados
    writer.writerows(compras)
print("Arquivo CSV gerado com sucesso!")
warnings.filterwarnings('ignore')

Arquivo CSV gerado com sucesso!

In [11]:
# Fechar a conexão
conn.close()

In [12]:
# Importar o arquivo e visualizar
DadosCompras = pd.read_csv('registros.csv', low_memory = False)
DadosCompras.head(15)

,ID Cliente,Cliente,Idade,Telefone,Estado,DataCompra,Produto,Preço,Unidades,ValorCompra
0,1,Isis Cavalcanti,29,(83) 88261719,Paraíba,2024-12-27,chaveiro,5.75,2,11.5
1,2,Isabelly Pastor,47,(45) 84963897,Paraná,2024-12-13,Pendrive,34.90,8,279.2
2,3,Gabriela Duarte,48,(62) 89956084,Goiás,2024-12-26,Mangá,36.90,2,73.8
3,4,Lara Vargas,47,(92) 26338457,Amazonas,2024-12-14,pijama,85.90,8,687.2
4,5,Alana Araújo,29,(61) 65788798,Distrito Federal,2024-12-07,Teclado,49.90,7,349.3
5,6,Isabelly Andrade,18,(95) 43392447,Roraima,2024-12-05,Mangá,36.90,3,110.7
6,7,Heloisa Moreira,49,(63) 45204896,Tocantins,2024-12-05,Jogo de Festa,62.40,9,561.6
7,8,Pietra Ribeiro,22,(28) 93834039,Espírito Santo,2024-12-06,Funko Pop,80.50,1,80.5
8,9,Fernando Almeida,32,(47) 34817110,Santa Catarina,2024-12-29,Copo Térmico,39.90,4,159.6
9,10,Cauã Rezende,23,(37) 82949305,Minas Gerais,2024-12-04,pijama,85.90,5,429.5
10,11,João Lucas Oliveira,38,(68) 22995694,Acre,2024-12-05,Graphic Novel,49.90,5,249.5
11,12,Luiz Fernando Sales,39,(73) 94400650,Bahia,2024-12-10,Luminária personalizada,250.10,10,2501.0
12,13,Clarice Macedo,18,(45) 30934259,Paraná,2024-12-09,Coleção de Figurinhas,91.90,7,643.3
13,14,Esther Cunha,23,(16) 99077381,São Paulo,2024-12-07,Jogo de Estratégia,98.70,6,592.2
14,15,Luan Andrade,50,(79) 62868121,Sergipe,2024-12-04,Pendrive,34.90,1,34.9

## CONLCUSÃO:
Como resultado foram gerados dados de 2500 clientes incluindo: nome, idade, telefone, estado,data da compra, produto, preço, unidades compradas e valor gasto pelo cliente.